version: '3.8' 
services:
  app:
    image: sikander098/nodejs
    build:
      context: .
    ports:
      - "3005:5000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: mydb
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    restart: always
