name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step 1: Checkout code
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install Node.js dependencies
    - run: npm ci

    # Step 4: Build the project (if applicable)
    - run: npm run build --if-present

    # Step 5: Run tests
    - run: npm test

    # Step 6: Log in to Docker Hub using your Docker Hub password
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 7: Set up QEMU (optional for multi-architecture builds)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Step 8: Set up Docker Buildx (needed for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 9: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .  # Current directory (where Dockerfile is located)
        push: true   # Push the image to Docker Hub
        tags: sikander098/nodejs:latest  # Image name and tag 
